exec-once = waybar
exec-once = ~/.config/hypr/scripts/wallpaper
$HYPR_CONFIG_PATH = ~/.config/hypr/configs
source = $HYPR_CONFIG_PATH/tokyonight.conf
source = $HYPR_CONFIG_PATH/rice.conf
source = $HYPR_CONFIG_PATH/misc.conf
source = $HYPR_CONFIG_PATH/keybinds.conf
source = $HYPR_CONFIG_PATH/rules.conf


####################
### KEYBINDINGSS ###
####################


