monitor=eDP-1,1920x1080@60,auto,1.0
#monitor=eDP-1,1366x768@60,auto,1.0
#monitor=eDP-1,1600x900@60,auto,1.0

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    sensitivity = 0.1 
    touchpad {
        natural_scroll = true
    }
}

dwindle {
    pseudotile = true 
    preserve_split = true
}

master {
    new_is_master = false
}

misc {
    disable_hyprland_logo = true 
    disable_splash_rendering = true
    vfr = true
    enable_swallow = true
    swallow_regex = "$(kitty)^"
}

binds {
    allow_workspace_cycles = true
}


gestures {
    workspace_swipe = true
}


windowrulev2 = suppressevent maximize, class:.* 
windowrulev2 = float,class:^(xx)$
