general {
    gaps_in = 5
    gaps_out = 5

    border_size = 1

    col.active_border = $cyan $blue  25deg
    col.inactive_border = $dark3

    resize_on_border = false

    allow_tearing = false

    layout = pseudo
}

decoration {
    rounding = 10

    active_opacity = 1.0
    inactive_opacity = 0.9

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)

    blur {
        enabled = true
        size = 3
        passes = 1
        vibrancy = 0.1696
        ignore_opacity = true
    }
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = linear, 0.0, 0.0, 1.0, 1.0
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = borderangle, 1, 100, linear, loop
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}


